=== 4evrthng/MIF/IT/2/XMLSchema2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.imdb.com/movies" 
		   xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ac="http://www.imdb.com/movies" 
		   targetNamespace="http://www.imdb.com/movies" elementFormDefault="qualified">
	<xs:annotation >
		<xs:documentation xml:lang="en">
		Movies xml schema
		</xs:documentation>
	</xs:annotation>

	<xs:element name="movies" type="MoviesType">

	</xs:element>
<!--Types-->	
	<xs:complexType name="MoviesType">
		<xs:sequence>
			<xs:element name = "movie" type = "MovieType" maxOccurs="unbounded">
				<!-- 8 -->
				<xs:unique name ="MovieActorsName" >
					<xs:selector xpath="ac:starring"/>
					<xs:field xpath ="@as"/>
				</xs:unique>
				<xs:keyref name="KeyStarring" refer="MovieActorsName" >
					<xs:selector xpath="."/>
					<xs:field xpath="@lng"/>
				</xs:keyref>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="MovieType">
		<xs:sequence>
			<xs:element name = "userScores" type="userScoreType"/>
			<!-- 7 -->
			<xs:choice maxOccurs="1">
				<xs:element name="geras" type="ImpressionsType"/>
				<xs:element name="blogas" type="ImpressionsType"/>
				<xs:element name="fantastiskas" type="ImpressionsType"/>
			</xs:choice>
			<xs:element name = "directedBy" type="DirectorsExtendedRestrictedType"/>
			<xs:element name = "screenplayBy" maxOccurs="unbounded"/>
			<xs:element name = "starring"  type="StarringType" maxOccurs="5" />
			<xs:element name = "musicBy" />
			<xs:element name = "releaseDate" type="ReleaseDateType"/>
			<xs:element name = "language" type="xs:string" maxOccurs="10" />
			<xs:element name = "budget" type="BudgetType"/>
			<xs:element name = "plot" type="PlotExtendedRestrictedType"/>
			<xs:element name = "nominations" type="NominationsType"/>
		</xs:sequence>
		<xs:attribute name="lng" type="xs:string"/>
		<xs:attribute name="name" type = "xs:string"/>
		<xs:attribute name="IMDB" type = "xs:decimal"/>
	</xs:complexType>
<!-- 1 -->	
	<xs:simpleType name="ImpressionsType">
		<xs:restriction base="xs:string">
			<xs:minLength value="0"/>
		</xs:restriction>
	</xs:simpleType>
<!-- 2 -->
	<xs:simpleType name="userScoreType">
		<xs:list itemType="xs:integer"/>
	</xs:simpleType>
	
	<xs:complexType name="StarringType" mixed="true">
		<xs:attribute name="as" type = "xs:string"/>
	</xs:complexType>

	<xs:complexType name="ReleaseDateType" mixed="true">
		<xs:attribute name="country" type = "xs:string"/>
	</xs:complexType>

	<xs:complexType name="BudgetType" mixed="true">
		<xs:attribute name="currency" type = "xs:string"/>
	</xs:complexType>

	<xs:complexType name="PlotType" mixed="true">
		<xs:attribute name="writtenBy" type = "xs:string"/>
	</xs:complexType>

	
	<xs:complexType name="NominationsType">
		<xs:sequence>
			<xs:element name = "award" maxOccurs="unbounded" minOccurs="0">
				<xs:complexType >
					<xs:sequence>
						<xs:element name = "subject" minOccurs="0" maxOccurs="unbounded" type="SubjectType"/>					
					</xs:sequence>
					<xs:attribute name="name" type = "xs:string"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="SubjectType">
		<xs:sequence>
			<xs:element name="nominee" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="name" type = "xs:string"/>
		<xs:attribute name="result" type = "xs:string"/>
	</xs:complexType>
	<xs:simpleType name="DirectorType">
		<xs:restriction base="xs:string">
			<xs:minLength value="5"/>
		</xs:restriction>
	</xs:simpleType>
<!-- 3 -->
	<xs:complexType name="DirectorsExtendedType" >
		<xs:simpleContent>
			<xs:extension base="DirectorType">
				<xs:attribute name="pravarde" use="optional"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>


	<xs:complexType name="DirectorsExtendedRestrictedType">
		<xs:simpleContent>
			<xs:restriction base="DirectorsExtendedType">
				<xs:maxLength value="256"/>
			</xs:restriction>
		</xs:simpleContent>
	</xs:complexType>
<!-- 4 ir 6 -->
	<xs:complexType name="PlotExtendedType" mixed ="true">
		<xs:complexContent >
			<xs:extension base="PlotType">
				<xs:attribute name="EEEmakarena" use="optional"/>
			</xs:extension>
		</xs:complexContent>
		
	</xs:complexType>

	<xs:complexType name="PlotExtendedRestrictedType" mixed="true">
		<xs:complexContent >
			<xs:restriction base="PlotExtendedType">
				<xs:attribute name="EEEmakarena" type="xs:int"/>
			</xs:restriction>
		</xs:complexContent>

	</xs:complexType>
	
</xs:schema>

=== 4evrthng/MIF/IT/2/XML2.xml
<?xml version="1.0"?>
<?xml-stylesheet href="transf.xslt" type="text/xsl"?>
<movies xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.imdb.com/movies XMLSchema2.xsd">
	<movie lng="Anton" name="In a Better World" IMDB="7.7" >
		<userScores>1 2 3 4 5 6 7</userScores>
		<geras/>
		<directedBy>Susanne Bier</directedBy>
		<screenplayBy>Anders Thomas Jensen</screenplayBy>
		<starring as="Anton">Mikael Persbrandt</starring>
		
		<starring as="Marianne">Trine Dyrholm</starring>
		<starring as="Claus">Ulrich Thomsen</starring>
		<starring as="Jonathan Carnahan">John Hannah</starring>
		<musicBy>	</musicBy>
		<releaseDate country="Dennmark">2010.08.26</releaseDate>
		<language>Danish</language>
		<language>Swedish</language>
		<language>English</language>
		<language>Arabic</language>
		<language>Catalan</language>
		<language>Spanish</language>
		<budget currency="DKK">30000000</budget>
		<plot writtenBy="sisse-graum">The story traces  elements from a drab refugee camp in Sudan to the gray humdrum of everyday life in a Danish provincial town. The lives of two Danish families cross each other, and an extraordinary but risky friendship comes into bud. But loneliness, frailty and sorrow lie in wait. Soon, friendship transforms into a dangerous alliance and a breathtaking pursuit in which life is at stake.</plot>
		<nominations>
			<award name="Academy Awards">
				<subject name="Best Foreign Language Film" result="won"/>
			</award>
			
			<award name="Rome International Film Festival 2010">
				<subject name="Marc Aurelio Audience Award for Best Film" result="won"/>
				<subject name="Marc Aurelio Grand Jury Award" result="won"/>
			</award>
			<superaward>
				
			</superaward>
		</nominations>
	</movie>
	
	<movie name="The Mummy" IMDB="7.0">
		<userScores>7 8 9 9 6 7</userScores>
		<blogas/>
		<directedBy>Stephen Sommers</directedBy>
		<screenplayBy>Sean Daniel</screenplayBy>
		<screenplayBy>James Jacks</screenplayBy>
		<starring as="Anton">Mikael Persbrandt</starring>
		<starring as="Rick O'Connell">Brendan Fraser</starring>
		<starring as="Evelyn Carnahan">Rachel Weisz</starring>
		
		<starring as="High Priest Imhotep">Arnold Vosloo</starring>
		<starring as="Beni Gabor">Jonathan Hyde</starring>
		<musicBy>Jerry Goldsmith</musicBy>
		<releaseDate country="United States">1999.05.07</releaseDate>
		<language>English</language>
		<budget currency="$">80000000</budget>
		<plot writtenBy="Film_Fan" EEEmakarena="45">
		An English librarian called Evelyn Carnahan becomes interested in starting an archaeological dig at the ancient city of Hamunaptra. She gains the help of Rick O'Connell, after saving him from his death. What Evelyn, her brother Jonathan and Rick are unaware of is that another group of explorers are interested in the same dig. Unfortunately for everyone, this group ends up unleashing a curse which been laid on the dead High Priest Imhotep. Now 'The Mummy' is awake and it's going to take a lot more than guns to send him back from where he came from.</plot>
		<nominations>
			<award name="Academy Awards">
				<subject name="Best Sound Mixing" result="Nominated">
					<nominee>Leslie Shatz</nominee>
					<nominee>Chris Carpenter</nominee>
					<nominee>Rick Kline</nominee>
					<nominee>Chris Munro</nominee>
				</subject>
			</award>
			<award name="MTV Movie Awards">
				<subject name="Best Action Sequence" result="Nominated">
					
				</subject>
			</award>
				<award name="Golden Reel Awards">
				<subject name="Best Sound Editing - Effects and Foley" result="Nominated">
					<nominee>Mark Pappas</nominee>
					<nominee>Thom Brennan</nominee>
					<nominee>Richard Burton</nominee>
					<nominee>Jonathan Klein</nominee>
					<nominee>Leslie Shatz</nominee>
				</subject>
			</award>
			<superaward/>
		</nominations>
	</movie>
</movies>
